
spring:
  datasource:
    username: postgres
    password: nxbsin60w5
    url: jdbc:postgresql://localhost:5433/pmsystem
  application:
    name: pmsystem
server:
  port: 9001
  address: localhost
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secretKey: FOX9idUe0J04YxvesphlWBBWk/s+8G6KIw7fatc+ZsgpEuBkY9HOVfV6DJC09UdnjCqcXZnxQ6zp9rLFSEy1hw==
  expiration: 7200000
  tokenName: token